### ISSUE TITLE
Add Templates for commonly used patterns

### ISSUE THREAD

**Issue by AlanFoster** [AlanFoster/Camelry#30]
I believe IntelliJ allows you to register templates (possibly called LiveTemplates?) to automatically generate and insert common pieces of code.

It would be great to easily generate this boilerplate code for content based routers, aggregators, etc

It will be cool to check that out and see what we can do :)

**Comment by stibi** [comment]
Hi !
I have already prepared such templates in IntelliJ for Camel EIPs.
So if you don't mind, I can check the possibilities how to do this programatically by this plugin.

**Comment by AlanFoster** [comment]
Hey :)

That would be really awesome; I think this would really help out everyone a lot!

Cheers

**Comment by AlanFoster** [comment]
Hey @stibi how are you getting on with this one? :)
I've just had a look at this to see if I could help out with this; And from what I can see these steps might be useful
- Exporting your existing Live Template settings
  - Go to `File -> Export Settings` to create a `.settings.jar`, which should by default should export your live templates
  - Extract the live templates xml file from the created settings.jar with winrar/7zip etc
  - Place the generated xml file into the plugin resources folder under `liveTemplates`
- Register with the `defaultLiveTemplatesProvider` extension point in the plugin.xml with a class which implements `DefaultLiveTemplatesProvider` and points to your generated templates file
- Adding a new template context - this might be useful for specifically allowing templates to work under a certain element, like `cbr` under a camel route etc
  - Add an extension for `liveTemplateContext` and provide a class which extends `TemplateContextType` 
  - Update your generated templates file and add extra info under the `context` element

This is definitely gonna be a great feature to add, let me know how you get on with this :)

**Comment by AlanFoster** [comment]
Hey @stibi,

I've gone ahead and added some basic live templates to the plugin to get the ball rolling with this issue.

I've added a quick bit of documentation on the two new camel TemplateContexts i've created [here](https://github.com/AlanFoster/Camelry/blob/master/currentlySupported.md#live-templates), so if you have any ideas for a new live template, just fire up a new issue/PR :)

Cheers,
Alan
