### ISSUE TITLE
Add some developer documentation

### ISSUE THREAD

**Issue by AlanFoster** [AlanFoster/Camelry#36]
It would be great to add some developer documentation to help out contributors :)

It would be good to document some of the following
- [x] Information on getting the sourcecode into IntelliJ and debugging the plugin
- [x] Add tooling information for language contributions, ie bnf/flex support

**Comment by stibi** [comment]
This is good one. I started yesterday, finally, with setup of my environment and reading "writing IntelliJ plugins" articles on web..
Btw, what is the Java version for Intellij plugin development? JDK 1.7? I saw somewhere that 1.6 is recommended. But I was not able to compile the plugin with 1.6.

**Comment by AlanFoster** [comment]
Hey, @stibi that's great to hear! I've also added some useful articles on the front page about IntelliJ plugin development that might help you out too :)

I have been developing with Java SE JDK 7u25 at the minute - which has been working great in Win7/8 and Ubuntu. I've found the important thing is using the IDEA SDK though! I have added some information about [selecting your Project SDK](https://github.com/AlanFoster/Camelus/blob/master/developerSetupGuide.md#step-4-select-project-sdk) and there's also some useful information about this [here](http://confluence.jetbrains.com/display/IntelliJIDEA/Prerequisites) too.

Hopefully that'll help you get set up for development :)

**Comment by stibi** [comment]
Ok I have the environment ready now, but I noticed few troubles following your guide.
When I follow the guide, the Camelus project is imported into IntelliJ Idea as "Java module" project instead of "Plugin" project.
Then you are not able to create "Run configuration" as you don't have any "Plugin" modules in classpath.

So, what I did just create new project, as its type choose "IntelliJ Platform Plugin", as a project location use cloned Camelus sources.
Only one more step is add "gen/" directory as project sources, in project structure/modules configuration.

**Comment by AlanFoster** [comment]
Thanks for the feedback! From what I understand the *.iml file is supposed to contain all of the needed information, such as whether or not 'gen' is a src directory. If this causes any issues again I think we'll have to commit the .idea folder - like what the IntelliJ examples do. 

Let me know if you hit any more issues :)

**Comment by AlanFoster** [comment]
I think i'll go ahead and commit the `.idea` folder in the future, as the [IntelliJ project documentation](http://www.jetbrains.com/idea/webhelp/project.html#newProjectFormat) mentions that it may be useful to commit this directory, excluding the workspace.xml file. So hopefully that will stop any of the issues you faced @stibi 

Of course, if we move over to Maven we'll just drop the folder! :)

**Comment by AlanFoster** [comment]
Now that we have upgraded to use maven, I have updated the developer documentation under issue #51
