### ISSUE TITLE
Support for blueprint config PID file

### ISSUE THREAD

**Issue by tpines** [AlanFoster/Camelry#61]
If a blueprint's property-placeholder's persistent-id file is found on the classpath, any property values contained within it should used instead of the associated default-properties.

The plugin is extremely helpful. Unfortunately, not supporting the config PID requires creating corresponding defaults for every property one uses that is defined in the cfg file, else the references are redlined as undefined.

**Comment by AlanFoster** [comment]
Hey, thanks for the positive feedback @tpines  - I definitely think this would be a good idea to add!
Unfortunately I can't begin work on this feature, however I would be happy to accept any PRs to add support for this! :)

**Comment by tpines** [comment]
On 4/16/2014 9:08 AM, Alan Foster wrote:

> Hey, thanks for the positive feedback @tpines 
> https://github.com/tpines - I definitely think this would be a good 
> idea to add!
> Unfortunately I can't begin work on this feature, however I would be 
> happy to accept any PRs to add support for this! :)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/AlanFoster/Camelry/issues/61#issuecomment-40618282.
> 
> Unfortunately, I'm already over-committed (as probably are you :-) ).

Considering IntelliJ's lack of blueprint support and the excellent 
jump-start you've provided, I'd hoped JetBrains would have contacted you 
by now regarding adding it to their supported plugins and taken over 
enhancements. I would think adding it (with enhancements) to their 
Ultimate version would provide some marketing incentive and provide you 
with some much deserved remuneration. Although, I have no idea how 
JetBrains handles such things.

Cheers,
Tom
