### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by Waize** [AlanFoster/Camelry#66]
Hey,

is this repo still maintained? 
This plugins throws errors sometimes and I'm not sure if it will bring some changes if I am posting them here.

**Comment by AlanFoster** [comment]
Unfortunately I am not actively developing with Camel these days @Waize 

However - I believe that https://github.com/camel-idea-plugin/camel-idea-plugin is the latest offering for Camel + IntelliJ support - but I am not sure what it offers in terms of Spring/Blueprint

cc @davsclaus Is there blueprint support in the new camel-idea-plugin? If so - I can update this project's read me to point to the official plugin :+1:

**Comment by davsclaus** [comment]
The Camel IDEA plugin supports editing any Camel endpoint in XML and Java files etc. But it has no specific support for OSGi blueprint to assist configuring `<bean>` etc - that is not an Apache Camel specific thing, its general OSGi blueprint and that is out of the scope of our plugin. 

However anything you can edit inside `<camelContext>` is in the scope of our plugin, and we do not yet have support for selecting bean methods. 

I added a ticket to try to add support for assisting bean method names: https://github.com/camel-idea-plugin/camel-idea-plugin/issues/318

**Comment by Waize** [comment]
Thanks for your answers! 
I will have a look at the camel-idea-plugin soon and hope the bluepring support will come :)
